"""Add missing constraints and indexes

Revision ID: 1779b2c0243f
Revises: d84b991715d6
Create Date: 2026-02-12 14:49:22.827718

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1779b2c0243f'
down_revision: Union[str, None] = 'd84b991715d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_bgp_sessions_rs_conn', 'bgp_sessions', ['route_server_id', 'connection_id'], unique=False)
    op.create_index('ix_events_type_ixp', 'events', ['type', 'ixp_id'], unique=False)
    op.create_unique_constraint('uq_route_servers_ixp_id_hostname', 'route_servers', ['ixp_id', 'hostname'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_route_servers_ixp_id_hostname', 'route_servers', type_='unique')
    op.drop_index('ix_events_type_ixp', table_name='events')
    op.drop_index('ix_bgp_sessions_rs_conn', table_name='bgp_sessions')
    # ### end Alembic commands ###
