"""Add route_server_templates table with seed data

Revision ID: a3b4c5d6e7f8
Revises: ebae9caa1810
Create Date: 2026-03-26
"""

import uuid

import sqlalchemy as sa

from alembic import op

revision: str = "a3b4c5d6e7f8"
down_revision: str | None = "ebae9caa1810"
branch_labels: str | None = None
depends_on: str | None = None

# Seed template content embedded from src/ixforge/services/templates/bird/

SEED_TEMPLATES = [
    {
        "filename": "bird_v4.conf.j2",
        "description": "Main BIRD 2.x IPv4 route server configuration",
        "is_protected": True,
        "content": r"""# BIRD 2.x IPv4 configuration for {{ route_server.name }}
# Generated by IXForge Core at {{ generated_at }}
# Config hash: {{ config_hash }}
# DO NOT EDIT MANUALLY - this file is managed by IXForge

log syslog all;
log stderr { error, fatal };

router id {{ route_server.ip_v4 }};

protocol device {
    scan time 10;
}

protocol kernel {
    ipv4 {
        export none;
        import none;
    };
}

protocol direct {
    disabled;
}

# Common functions
{% include "functions/common.j2" %}

# Bogon prefix filters
{% with af=4 %}
{% include "filters/bogons.j2" %}
{% endwith %}

# BGP peers
{% for peer in peers %}
{% with af=4 %}
{% include "protocols/bgp_peer.j2" %}
{% endwith %}

{% endfor %}""",
    },
    {
        "filename": "bird_v6.conf.j2",
        "description": "Main BIRD 2.x IPv6 route server configuration",
        "is_protected": True,
        "content": r"""# BIRD 2.x IPv6 configuration for {{ route_server.name }}
# Generated by IXForge Core at {{ generated_at }}
# Config hash: {{ config_hash }}
# DO NOT EDIT MANUALLY - this file is managed by IXForge

log syslog all;
log stderr { error, fatal };

router id {{ route_server.router_id }};

protocol device {
    scan time 10;
}

protocol kernel {
    ipv6 {
        export none;
        import none;
    };
}

protocol direct {
    disabled;
}

# Common functions
{% include "functions/common.j2" %}

# Bogon prefix filters
{% with af=6 %}
{% include "filters/bogons.j2" %}
{% endwith %}

# BGP peers
{% for peer in peers %}
{% with af=6 %}
{% include "protocols/bgp_peer.j2" %}
{% endwith %}

{% endfor %}""",
    },
    {
        "filename": "protocols/bgp_peer.j2",
        "description": "BGP peer protocol block for BIRD route servers",
        "is_protected": False,
        "content": r"""# BGP peer: {{ peer.member_name | bird_str }} (AS{{ peer.peer_asn }})
protocol bgp {{ peer.protocol_name }} {
    local as {{ route_server.asn }};
    neighbor {{ peer.peer_ip }} as {{ peer.peer_asn }};
    description "{{ peer.member_name | bird_str }}";

    hold time 90;
    keepalive time 30;
    graceful restart on;

    {% if af == 4 %}
    ipv4 {
        import filter {
            if is_bogon_v4() then reject;
            if !net_len_valid(4) then reject;
            honor_graceful_shutdown();
            accept;
        };
        export filter {
            if is_bogon_v4() then reject;
            accept;
        };
        {% if peer.max_prefixes %}
        receive limit {{ peer.max_prefixes }} action restart;
        {% endif %}
    };
    {% endif %}

    {% if af == 6 %}
    ipv6 {
        import filter {
            if is_bogon_v6() then reject;
            if !net_len_valid(6) then reject;
            honor_graceful_shutdown();
            accept;
        };
        export filter {
            if is_bogon_v6() then reject;
            accept;
        };
        {% if peer.max_prefixes %}
        receive limit {{ peer.max_prefixes }} action restart;
        {% endif %}
    };
    {% endif %}
}""",
    },
    {
        "filename": "protocols/static.j2",
        "description": "Static blackhole routes protocol block",
        "is_protected": False,
        "content": r"""# Static routes for IXForge route servers
# Generated by IXForge Core - do not edit manually

{% if af == 4 %}
protocol static blackhole_v4 {
    ipv4 { preference 0; };
    # Blackhole routes for prefix filtering
    {% for route in blackhole_routes_v4 | default([]) %}
    route {{ route }} blackhole;
    {% endfor %}
}
{% endif %}

{% if af == 6 %}
protocol static blackhole_v6 {
    ipv6 { preference 0; };
    # Blackhole routes for prefix filtering
    {% for route in blackhole_routes_v6 | default([]) %}
    route {{ route }} blackhole;
    {% endfor %}
}
{% endif %}""",
    },
    {
        "filename": "functions/common.j2",
        "description": "Common BIRD functions (prefix length validation, graceful shutdown)",
        "is_protected": False,
        "content": r"""# Common BIRD functions for IXForge route servers
# Generated by IXForge Core - do not edit manually

function net_len_valid(int afi) {
    if afi = 4 then {
        if net.len > 24 then return false;
        if net.len < 8 then return false;
    }
    if afi = 6 then {
        if net.len > 48 then return false;
        if net.len < 12 then return false;
    }
    return true;
}

function honor_graceful_shutdown() {
    if (65535, 0) ~ bgp_community then {
        bgp_local_pref = 0;
    }
}""",
    },
    {
        "filename": "filters/bogons.j2",
        "description": "Bogon prefix filter definitions (IPv4 and IPv6)",
        "is_protected": False,
        "content": r"""# Bogon prefix filters for IXForge route servers
# Generated by IXForge Core - do not edit manually

{% if af == 4 %}
define BOGONS_V4 = [
    0.0.0.0/0,              # Default route
    0.0.0.0/8+,             # RFC 1122 "This host on this network"
    10.0.0.0/8+,            # RFC 1918 Private-Use
    100.64.0.0/10+,         # RFC 6598 Shared Address Space
    127.0.0.0/8+,           # RFC 1122 Loopback
    169.254.0.0/16+,        # RFC 3927 Link-Local
    172.16.0.0/12+,         # RFC 1918 Private-Use
    192.0.0.0/24+,          # RFC 6890 IETF Protocol Assignments
    192.0.2.0/24+,          # RFC 5737 Documentation (TEST-NET-1)
    192.168.0.0/16+,        # RFC 1918 Private-Use
    198.18.0.0/15+,         # RFC 2544 Benchmarking
    198.51.100.0/24+,       # RFC 5737 Documentation (TEST-NET-2)
    203.0.113.0/24+,        # RFC 5737 Documentation (TEST-NET-3)
    224.0.0.0/3+            # RFC 5771 Multicast + RFC 1112 Reserved
];

function is_bogon_v4() {
    if net ~ BOGONS_V4 then return true;
    return false;
}
{% endif %}

{% if af == 6 %}
define BOGONS_V6 = [
    ::/0,                   # Default route
    ::/8+,                  # RFC 4291 Unspecified and Loopback
    0100::/64+,             # RFC 6666 Discard-Only
    2001:2::/48+,           # RFC 5180 Benchmarking
    2001:db8::/32+,         # RFC 3849 Documentation
    2001:10::/28+,          # RFC 4843 ORCHID
    3ffe::/16+,             # RFC 3701 Former 6bone
    fc00::/7+,              # RFC 4193 Unique-Local
    fe80::/10+,             # RFC 4291 Link-Local
    fec0::/10+,             # RFC 3879 Site-Local (deprecated)
    ff00::/8+               # RFC 4291 Multicast
];

function is_bogon_v6() {
    if net ~ BOGONS_V6 then return true;
    return false;
}
{% endif %}""",
    },
    {
        "filename": "filters/communities.j2",
        "description": "BGP community filter definitions (graceful shutdown, blackhole)",
        "is_protected": False,
        "content": r"""# BGP community filters for IXForge route servers
# Generated by IXForge Core - do not edit manually

{% if af == 4 %}
# Informational communities (RFC 8326 / RFC 7999)
define IXP_ASN = {{ route_server.asn }};

# Graceful shutdown (RFC 8326)
define GRACEFUL_SHUTDOWN = (65535, 0);

# Blackhole (RFC 7999)
define BLACKHOLE_COMMUNITY = (65535, 666);

# honor_graceful_shutdown() is defined in functions/common.j2

function is_blackhole_request() {
    if (BLACKHOLE_COMMUNITY ~ bgp_community) then return true;
    return false;
}
{% endif %}

{% if af == 6 %}
# Informational communities (RFC 8326 / RFC 7999)
define IXP_ASN = {{ route_server.asn }};

# Graceful shutdown (RFC 8326)
define GRACEFUL_SHUTDOWN = (65535, 0);

# Blackhole (RFC 7999)
define BLACKHOLE_COMMUNITY = (65535, 666);

# honor_graceful_shutdown() is defined in functions/common.j2

function is_blackhole_request() {
    if (BLACKHOLE_COMMUNITY ~ bgp_community) then return true;
    return false;
}
{% endif %}""",
    },
]


def upgrade() -> None:
    op.create_table(
        "route_server_templates",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("ixp_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
        sa.Column("filename", sa.String(255), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("description", sa.String(500), nullable=True),
        sa.Column("is_protected", sa.Boolean(), nullable=False, server_default=sa.text("false")),
        sa.Column("updated_by_id", sa.Uuid(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["ixp_id"], ["ixps.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["updated_by_id"], ["users.id"], ondelete="SET NULL"),
        sa.UniqueConstraint("ixp_id", "filename", name="uq_rs_templates_ixp_filename"),
    )
    op.create_index("ix_route_server_templates_ixp_id", "route_server_templates", ["ixp_id"])

    # Seed templates for every existing IXP
    conn = op.get_bind()
    ixps = conn.execute(sa.text("SELECT id FROM ixps")).fetchall()

    for ixp_row in ixps:
        ixp_id = ixp_row[0]
        for tmpl in SEED_TEMPLATES:
            conn.execute(
                sa.text(
                    "INSERT INTO route_server_templates "
                    "(id, ixp_id, filename, content, description, is_protected) "
                    "VALUES (:id, :ixp_id, :filename, :content, :description, :is_protected)"
                ),
                {
                    "id": str(uuid.uuid4()),
                    "ixp_id": str(ixp_id),
                    "filename": tmpl["filename"],
                    "content": tmpl["content"],
                    "description": tmpl["description"],
                    "is_protected": tmpl["is_protected"],
                },
            )


def downgrade() -> None:
    op.drop_index("ix_route_server_templates_ixp_id", table_name="route_server_templates")
    op.drop_table("route_server_templates")
