"""parity_patagoniaix

Revision ID: bfd548e1dcec
Revises: b3f8a1c42d97
Create Date: 2026-03-03 19:51:03.548625

"""
from collections.abc import Sequence

import sqlalchemy as sa

import ixforge.models.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bfd548e1dcec'
down_revision: str | None = 'b3f8a1c42d97'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("ALTER TYPE vlan_type ADD VALUE IF NOT EXISTS 'private'")
    op.create_table('asn_cache',
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False, comment='UTC timestamp of last PeeringDB fetch'),
    sa.PrimaryKeyConstraint('asn')
    )
    op.create_table('locations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("country ~ '^[A-Z]{2}$'", name='ck_locations_country_iso'),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ixp_id', 'name', name='uq_locations_ixp_id_name')
    )
    op.create_index(op.f('ix_locations_ixp_id'), 'locations', ['ixp_id'], unique=False)
    op.create_table('route_server_vlans',
    sa.Column('route_server_id', sa.Uuid(), nullable=False),
    sa.Column('vlan_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_server_id'], ['route_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_server_id', 'vlan_id', name='uq_route_server_vlans')
    )
    op.create_index(op.f('ix_route_server_vlans_ixp_id'), 'route_server_vlans', ['ixp_id'], unique=False)
    op.create_index(op.f('ix_route_server_vlans_route_server_id'), 'route_server_vlans', ['route_server_id'], unique=False)
    op.create_index(op.f('ix_route_server_vlans_vlan_id'), 'route_server_vlans', ['vlan_id'], unique=False)
    op.create_table('vlan_members',
    sa.Column('vlan_id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vlan_id', 'member_id', name='uq_vlan_members')
    )
    op.create_index(op.f('ix_vlan_members_ixp_id'), 'vlan_members', ['ixp_id'], unique=False)
    op.create_index(op.f('ix_vlan_members_member_id'), 'vlan_members', ['member_id'], unique=False)
    op.create_index(op.f('ix_vlan_members_vlan_id'), 'vlan_members', ['vlan_id'], unique=False)
    op.create_table('rs_ip_assignments',
    sa.Column('route_server_id', sa.Uuid(), nullable=False),
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('address', ixforge.models.types.INET(), nullable=False),
    sa.Column('af', sa.Integer(), nullable=False, comment='Address family: 4 or 6'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('af IN (4, 6)', name='ck_rs_ip_assignments_af_valid'),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['ip_pools.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['route_server_id'], ['route_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address'),
    sa.UniqueConstraint('route_server_id', 'af', name='uq_rs_ip_assignments_rs_af')
    )
    op.create_index(op.f('ix_rs_ip_assignments_ixp_id'), 'rs_ip_assignments', ['ixp_id'], unique=False)
    op.create_index(op.f('ix_rs_ip_assignments_pool_id'), 'rs_ip_assignments', ['pool_id'], unique=False)
    op.create_index(op.f('ix_rs_ip_assignments_route_server_id'), 'rs_ip_assignments', ['route_server_id'], unique=False)
    op.add_column('members', sa.Column('member_type', sa.String(length=50), nullable=True))
    op.add_column('members', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('city', sa.String(length=255), nullable=True))
    op.add_column('members', sa.Column('country', sa.String(length=2), nullable=True))
    op.add_column('members', sa.Column('connection_date', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('contract_start', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('contract_renewal', sa.Date(), nullable=True))
    op.add_column('members', sa.Column('contract_type', sa.String(length=20), nullable=True))
    op.add_column('members', sa.Column('notes', sa.Text(), nullable=True))
    op.add_column('members', sa.Column('skip_ixf_export', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('switches', sa.Column('location_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'switches', 'locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('phone', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('position', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('pgp_key', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # Removing 'private' from vlan_type requires recreating the type — not implemented
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pgp_key')
    op.drop_column('users', 'position')
    op.drop_column('users', 'phone')
    op.drop_constraint(None, 'switches', type_='foreignkey')
    op.drop_column('switches', 'location_id')
    op.drop_column('members', 'skip_ixf_export')
    op.drop_column('members', 'notes')
    op.drop_column('members', 'contract_type')
    op.drop_column('members', 'contract_renewal')
    op.drop_column('members', 'contract_start')
    op.drop_column('members', 'connection_date')
    op.drop_column('members', 'country')
    op.drop_column('members', 'city')
    op.drop_column('members', 'description')
    op.drop_column('members', 'member_type')
    op.drop_index(op.f('ix_rs_ip_assignments_route_server_id'), table_name='rs_ip_assignments')
    op.drop_index(op.f('ix_rs_ip_assignments_pool_id'), table_name='rs_ip_assignments')
    op.drop_index(op.f('ix_rs_ip_assignments_ixp_id'), table_name='rs_ip_assignments')
    op.drop_table('rs_ip_assignments')
    op.drop_index(op.f('ix_vlan_members_vlan_id'), table_name='vlan_members')
    op.drop_index(op.f('ix_vlan_members_member_id'), table_name='vlan_members')
    op.drop_index(op.f('ix_vlan_members_ixp_id'), table_name='vlan_members')
    op.drop_table('vlan_members')
    op.drop_index(op.f('ix_route_server_vlans_vlan_id'), table_name='route_server_vlans')
    op.drop_index(op.f('ix_route_server_vlans_route_server_id'), table_name='route_server_vlans')
    op.drop_index(op.f('ix_route_server_vlans_ixp_id'), table_name='route_server_vlans')
    op.drop_table('route_server_vlans')
    op.drop_index(op.f('ix_locations_ixp_id'), table_name='locations')
    op.drop_table('locations')
    op.drop_table('asn_cache')
    # ### end Alembic commands ###
