"""initial schema

Revision ID: d84b991715d6
Revises:
Create Date: 2026-02-12 13:57:56.008628

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

import ixforge.models.types
from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd84b991715d6'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ixps',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('country', sa.String(length=2), nullable=True),
    sa.Column('city', sa.String(length=255), nullable=True),
    sa.Column('peeringdb_id', sa.Integer(), nullable=True),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('short_name')
    )
    op.create_table('custom_field_definitions',
    sa.Column('entity_type', sa.Enum('member', 'connection', 'port', 'switch', 'vlan', name='custom_field_entity_type'), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_type', sa.Enum('string', 'integer', 'boolean', 'url', 'email', name='custom_field_type'), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ixp_id', 'entity_type', 'field_name', name='uq_custom_fields_ixp_entity_field')
    )
    op.create_index(op.f('ix_custom_field_definitions_ixp_id'), 'custom_field_definitions', ['ixp_id'], unique=False)
    op.create_table('members',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=False),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('state', sa.Enum('prospect', 'provisioning', 'active', 'suspended', 'terminated', name='member_state'), nullable=False),
    sa.Column('peering_policy', sa.Enum('open', 'selective', 'restrictive', 'no', name='peering_policy'), nullable=False),
    sa.Column('peering_policy_details', sa.Text(), nullable=True),
    sa.Column('website', sa.String(length=512), nullable=True),
    sa.Column('peeringdb_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ixp_id', 'asn', name='uq_members_ixp_id_asn')
    )
    op.create_index(op.f('ix_members_ixp_id'), 'members', ['ixp_id'], unique=False)
    op.create_table('route_servers',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('ip_v4', ixforge.models.types.INET(), nullable=True),
    sa.Column('ip_v6', ixforge.models.types.INET(), nullable=True),
    sa.Column('asn', sa.Integer(), nullable=False),
    sa.Column('software', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_heartbeat_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('agent_version', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_route_servers_ixp_id'), 'route_servers', ['ixp_id'], unique=False)
    op.create_table('switches',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('hostname', sa.String(length=255), nullable=False),
    sa.Column('vendor', sa.String(length=100), nullable=True),
    sa.Column('model', sa.String(length=100), nullable=True),
    sa.Column('management_ip', ixforge.models.types.INET(), nullable=True),
    sa.Column('snmp_community_encrypted', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ixp_id', 'hostname', name='uq_switches_ixp_id_hostname')
    )
    op.create_index(op.f('ix_switches_ixp_id'), 'switches', ['ixp_id'], unique=False)
    op.create_table('vlans',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('vid', sa.Integer(), nullable=False, comment='VLAN ID'),
    sa.Column('type', sa.Enum('production', 'quarantine', 'management', 'other', name='vlan_type'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ixp_id', 'vid', name='uq_vlans_ixp_id_vid')
    )
    op.create_index(op.f('ix_vlans_ixp_id'), 'vlans', ['ixp_id'], unique=False)
    op.create_table('contacts',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('noc', 'admin', 'technical', 'billing', name='contact_role'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contacts_member_id'), 'contacts', ['member_id'], unique=False)
    op.create_table('ip_pools',
    sa.Column('vlan_id', sa.Uuid(), nullable=False),
    sa.Column('network', ixforge.models.types.CIDR(), nullable=False, comment='CIDR notation'),
    sa.Column('gateway', ixforge.models.types.INET(), nullable=False, comment='Gateway address'),
    sa.Column('af', sa.Integer(), nullable=False, comment='Address family: 4 or 6'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ip_pools_vlan_id'), 'ip_pools', ['vlan_id'], unique=False)
    op.create_table('ports',
    sa.Column('switch_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('speed', sa.Integer(), nullable=False, comment='Speed in Mbps'),
    sa.Column('type', sa.Enum('member', 'infra', 'unused', name='port_type'), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['switch_id'], ['switches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('switch_id', 'name', name='uq_ports_switch_id_name')
    )
    op.create_index(op.f('ix_ports_member_id'), 'ports', ['member_id'], unique=False)
    op.create_index(op.f('ix_ports_switch_id'), 'ports', ['switch_id'], unique=False)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'member', name='user_role'), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('api_keys',
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('prefix', sa.String(length=12), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('scopes', sa.ARRAY(sa.String()), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=True),
    sa.Column('route_server_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['route_server_id'], ['route_servers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('config_versions',
    sa.Column('route_server_id', sa.Uuid(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('config_hash', sa.String(length=64), nullable=False),
    sa.Column('template_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('generated_by_id', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['route_server_id'], ['route_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_config_versions_route_server_id'), 'config_versions', ['route_server_id'], unique=False)
    op.create_table('connections',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('port_id', sa.Uuid(), nullable=True),
    sa.Column('type', sa.Enum('physical', 'virtual', name='connection_type'), nullable=False),
    sa.Column('state', sa.Enum('draft', 'provisioning', 'active', 'disabled', 'decommissioned', name='connection_state'), nullable=False),
    sa.Column('mac_address', ixforge.models.types.MACADDR(), nullable=True),
    sa.Column('speed', sa.Integer(), nullable=True, comment='Speed in Mbps'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['port_id'], ['ports.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_connections_member_id'), 'connections', ['member_id'], unique=False)
    op.create_index(op.f('ix_connections_port_id'), 'connections', ['port_id'], unique=False)
    op.create_table('events',
    sa.Column('type', sa.String(length=100), nullable=False, comment='Event type, e.g. member.created'),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.Uuid(), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('ixp_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['ixp_id'], ['ixps.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_actor_id'), 'events', ['actor_id'], unique=False)
    op.create_index(op.f('ix_events_created_at'), 'events', ['created_at'], unique=False)
    op.create_index(op.f('ix_events_ixp_id'), 'events', ['ixp_id'], unique=False)
    op.create_index(op.f('ix_events_resource_id'), 'events', ['resource_id'], unique=False)
    op.create_index(op.f('ix_events_resource_type'), 'events', ['resource_type'], unique=False)
    op.create_table('bgp_sessions',
    sa.Column('route_server_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('peer_ip', ixforge.models.types.INET(), nullable=False),
    sa.Column('peer_asn', sa.Integer(), nullable=False),
    sa.Column('admin_state', sa.Enum('up', 'down', name='bgp_admin_state'), nullable=False),
    sa.Column('oper_state', sa.Enum('up', 'down', 'unknown', name='bgp_oper_state'), nullable=False),
    sa.Column('af', sa.Integer(), nullable=False, comment='Address family: 4 or 6'),
    sa.Column('max_prefixes', sa.Integer(), nullable=True),
    sa.Column('import_limit', sa.Integer(), nullable=True),
    sa.Column('export_limit', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['route_server_id'], ['route_servers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bgp_sessions_connection_id'), 'bgp_sessions', ['connection_id'], unique=False)
    op.create_index(op.f('ix_bgp_sessions_route_server_id'), 'bgp_sessions', ['route_server_id'], unique=False)
    op.create_table('connection_vlans',
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('vlan_id', sa.Uuid(), nullable=False),
    sa.Column('tagged', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vlan_id'], ['vlans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('connection_id', 'vlan_id', name='uq_connection_vlans_conn_vlan')
    )
    op.create_index(op.f('ix_connection_vlans_connection_id'), 'connection_vlans', ['connection_id'], unique=False)
    op.create_index(op.f('ix_connection_vlans_vlan_id'), 'connection_vlans', ['vlan_id'], unique=False)
    op.create_table('ip_assignments',
    sa.Column('pool_id', sa.Uuid(), nullable=False),
    sa.Column('connection_id', sa.Uuid(), nullable=False),
    sa.Column('address', ixforge.models.types.INET(), nullable=False, comment='IP address'),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connection_id'], ['connections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pool_id'], ['ip_pools.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_ip_assignments_connection_id'), 'ip_assignments', ['connection_id'], unique=False)
    op.create_index(op.f('ix_ip_assignments_pool_id'), 'ip_assignments', ['pool_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ip_assignments_pool_id'), table_name='ip_assignments')
    op.drop_index(op.f('ix_ip_assignments_connection_id'), table_name='ip_assignments')
    op.drop_table('ip_assignments')
    op.drop_index(op.f('ix_connection_vlans_vlan_id'), table_name='connection_vlans')
    op.drop_index(op.f('ix_connection_vlans_connection_id'), table_name='connection_vlans')
    op.drop_table('connection_vlans')
    op.drop_index(op.f('ix_bgp_sessions_route_server_id'), table_name='bgp_sessions')
    op.drop_index(op.f('ix_bgp_sessions_connection_id'), table_name='bgp_sessions')
    op.drop_table('bgp_sessions')
    op.drop_index(op.f('ix_events_resource_type'), table_name='events')
    op.drop_index(op.f('ix_events_resource_id'), table_name='events')
    op.drop_index(op.f('ix_events_ixp_id'), table_name='events')
    op.drop_index(op.f('ix_events_created_at'), table_name='events')
    op.drop_index(op.f('ix_events_actor_id'), table_name='events')
    op.drop_table('events')
    op.drop_index(op.f('ix_connections_port_id'), table_name='connections')
    op.drop_index(op.f('ix_connections_member_id'), table_name='connections')
    op.drop_table('connections')
    op.drop_index(op.f('ix_config_versions_route_server_id'), table_name='config_versions')
    op.drop_table('config_versions')
    op.drop_table('api_keys')
    op.drop_table('users')
    op.drop_index(op.f('ix_ports_switch_id'), table_name='ports')
    op.drop_index(op.f('ix_ports_member_id'), table_name='ports')
    op.drop_table('ports')
    op.drop_index(op.f('ix_ip_pools_vlan_id'), table_name='ip_pools')
    op.drop_table('ip_pools')
    op.drop_index(op.f('ix_contacts_member_id'), table_name='contacts')
    op.drop_table('contacts')
    op.drop_index(op.f('ix_vlans_ixp_id'), table_name='vlans')
    op.drop_table('vlans')
    op.drop_index(op.f('ix_switches_ixp_id'), table_name='switches')
    op.drop_table('switches')
    op.drop_index(op.f('ix_route_servers_ixp_id'), table_name='route_servers')
    op.drop_table('route_servers')
    op.drop_index(op.f('ix_members_ixp_id'), table_name='members')
    op.drop_table('members')
    op.drop_index(op.f('ix_custom_field_definitions_ixp_id'), table_name='custom_field_definitions')
    op.drop_table('custom_field_definitions')
    op.drop_table('ixps')
    # ### end Alembic commands ###
