"""Default BIRD templates installed for every new IXP.

La migracion a3b4c5d6e7f8 contiene un snapshot historico de estos mismos
templates para los IXPs que existian antes de esa revision. Esta es la
fuente canonica para IXPs nuevos creados via setup
"""

import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from ixforge.models.rs_template import RouteServerTemplate

DEFAULT_TEMPLATES: list[dict[str, object]] = [
    {
        "filename": "bird_v4.conf.j2",
        "description": "Main BIRD 2.x IPv4 route server configuration",
        "is_protected": True,
        "content": r"""# BIRD 2.x IPv4 configuration for {{ route_server.name }}
# Generated by IXForge Core at {{ generated_at }}
# Config hash: {{ config_hash }}
# DO NOT EDIT MANUALLY - this file is managed by IXForge

{% if include_globals | default(true) %}
log syslog all;
log stderr { error, fatal };

router id {{ route_server.router_id }};

protocol device {
    scan time 10;
}

protocol direct {
    disabled;
}

# Common functions
{% include "functions/common.j2" %}

{% endif %}
protocol kernel {
    ipv4 {
        export none;
        import none;
    };
}

# Bogon prefix filters
{% with af=4 %}
{% include "filters/bogons.j2" %}
{% endwith %}

# BGP peers
{% for peer in peers %}
{% with af=4 %}
{% include "protocols/bgp_peer.j2" %}
{% endwith %}

{% endfor %}""",
    },
    {
        "filename": "bird_v6.conf.j2",
        "description": "Main BIRD 2.x IPv6 route server configuration",
        "is_protected": True,
        "content": r"""# BIRD 2.x IPv6 configuration for {{ route_server.name }}
# Generated by IXForge Core at {{ generated_at }}
# Config hash: {{ config_hash }}
# DO NOT EDIT MANUALLY - this file is managed by IXForge

{% if include_globals | default(true) %}
log syslog all;
log stderr { error, fatal };

router id {{ route_server.router_id }};

protocol device {
    scan time 10;
}

protocol direct {
    disabled;
}

# Common functions
{% include "functions/common.j2" %}

{% endif %}
protocol kernel {
    ipv6 {
        export none;
        import none;
    };
}

# Bogon prefix filters
{% with af=6 %}
{% include "filters/bogons.j2" %}
{% endwith %}

# BGP peers
{% for peer in peers %}
{% with af=6 %}
{% include "protocols/bgp_peer.j2" %}
{% endwith %}

{% endfor %}""",
    },
    {
        "filename": "protocols/bgp_peer.j2",
        "description": "BGP peer protocol block for BIRD route servers",
        "is_protected": False,
        "content": r"""# BGP peer: {{ peer.member_name | bird_str }} (AS{{ peer.peer_asn }})
protocol bgp {{ peer.protocol_name }} {
    local as {{ route_server.asn }};
    neighbor {{ peer.peer_ip }} as {{ peer.peer_asn }};
    description "{{ peer.member_name | bird_str }}";

    hold time 90;
    keepalive time 30;
    graceful restart on;

    {% if af == 4 %}
    ipv4 {
        import filter {
            if is_bogon_v4() then reject;
            if !net_len_valid(4) then reject;
            honor_graceful_shutdown();
            accept;
        };
        export filter {
            if is_bogon_v4() then reject;
            accept;
        };
        {% if peer.max_prefixes %}
        receive limit {{ peer.max_prefixes }} action restart;
        {% endif %}
    };
    {% endif %}

    {% if af == 6 %}
    ipv6 {
        import filter {
            if is_bogon_v6() then reject;
            if !net_len_valid(6) then reject;
            honor_graceful_shutdown();
            accept;
        };
        export filter {
            if is_bogon_v6() then reject;
            accept;
        };
        {% if peer.max_prefixes %}
        receive limit {{ peer.max_prefixes }} action restart;
        {% endif %}
    };
    {% endif %}
}""",
    },
    {
        "filename": "protocols/static.j2",
        "description": "Static blackhole routes protocol block",
        "is_protected": False,
        "content": r"""# Static routes for IXForge route servers
# Generated by IXForge Core - do not edit manually

{% if af == 4 %}
protocol static blackhole_v4 {
    ipv4 { preference 0; };
    # Blackhole routes for prefix filtering
    {% for route in blackhole_routes_v4 | default([]) %}
    route {{ route }} blackhole;
    {% endfor %}
}
{% endif %}

{% if af == 6 %}
protocol static blackhole_v6 {
    ipv6 { preference 0; };
    # Blackhole routes for prefix filtering
    {% for route in blackhole_routes_v6 | default([]) %}
    route {{ route }} blackhole;
    {% endfor %}
}
{% endif %}""",
    },
    {
        "filename": "functions/common.j2",
        "description": "Common BIRD functions (prefix length validation, graceful shutdown)",
        "is_protected": False,
        "content": r"""# Common BIRD functions for IXForge route servers
# Generated by IXForge Core - do not edit manually

function net_len_valid(int afi) {
    if afi = 4 then {
        if net.len > 24 then return false;
        if net.len < 8 then return false;
    }
    if afi = 6 then {
        if net.len > 48 then return false;
        if net.len < 12 then return false;
    }
    return true;
}

function honor_graceful_shutdown() {
    if (65535, 0) ~ bgp_community then {
        bgp_local_pref = 0;
    }
}""",
    },
    {
        "filename": "filters/bogons.j2",
        "description": "Bogon prefix filter definitions (IPv4 and IPv6)",
        "is_protected": False,
        "content": r"""# Bogon prefix filters for IXForge route servers
# Generated by IXForge Core - do not edit manually

{% if af == 4 %}
define BOGONS_V4 = [
    0.0.0.0/0,              # Default route
    0.0.0.0/8+,             # RFC 1122 "This host on this network"
    10.0.0.0/8+,            # RFC 1918 Private-Use
    100.64.0.0/10+,         # RFC 6598 Shared Address Space
    127.0.0.0/8+,           # RFC 1122 Loopback
    169.254.0.0/16+,        # RFC 3927 Link-Local
    172.16.0.0/12+,         # RFC 1918 Private-Use
    192.0.0.0/24+,          # RFC 6890 IETF Protocol Assignments
    192.0.2.0/24+,          # RFC 5737 Documentation (TEST-NET-1)
    192.168.0.0/16+,        # RFC 1918 Private-Use
    198.18.0.0/15+,         # RFC 2544 Benchmarking
    198.51.100.0/24+,       # RFC 5737 Documentation (TEST-NET-2)
    203.0.113.0/24+,        # RFC 5737 Documentation (TEST-NET-3)
    224.0.0.0/3+            # RFC 5771 Multicast + RFC 1112 Reserved
];

function is_bogon_v4() {
    if net ~ BOGONS_V4 then return true;
    return false;
}
{% endif %}

{% if af == 6 %}
define BOGONS_V6 = [
    ::/0,                   # Default route
    ::/8+,                  # RFC 4291 Unspecified and Loopback
    0100::/64+,             # RFC 6666 Discard-Only
    2001:2::/48+,           # RFC 5180 Benchmarking
    2001:db8::/32+,         # RFC 3849 Documentation
    2001:10::/28+,          # RFC 4843 ORCHID
    3ffe::/16+,             # RFC 3701 Former 6bone
    fc00::/7+,              # RFC 4193 Unique-Local
    fe80::/10+,             # RFC 4291 Link-Local
    fec0::/10+,             # RFC 3879 Site-Local (deprecated)
    ff00::/8+               # RFC 4291 Multicast
];

function is_bogon_v6() {
    if net ~ BOGONS_V6 then return true;
    return false;
}
{% endif %}""",
    },
    {
        "filename": "filters/communities.j2",
        "description": "BGP community filter definitions (graceful shutdown, blackhole)",
        "is_protected": False,
        "content": r"""# BGP community filters for IXForge route servers
# Generated by IXForge Core - do not edit manually

{% if af == 4 %}
# Informational communities (RFC 8326 / RFC 7999)
define IXP_ASN = {{ route_server.asn }};

# Graceful shutdown (RFC 8326)
define GRACEFUL_SHUTDOWN = (65535, 0);

# Blackhole (RFC 7999)
define BLACKHOLE_COMMUNITY = (65535, 666);

# honor_graceful_shutdown() is defined in functions/common.j2

function is_blackhole_request() {
    if (BLACKHOLE_COMMUNITY ~ bgp_community) then return true;
    return false;
}
{% endif %}

{% if af == 6 %}
# Informational communities (RFC 8326 / RFC 7999)
define IXP_ASN = {{ route_server.asn }};

# Graceful shutdown (RFC 8326)
define GRACEFUL_SHUTDOWN = (65535, 0);

# Blackhole (RFC 7999)
define BLACKHOLE_COMMUNITY = (65535, 666);

# honor_graceful_shutdown() is defined in functions/common.j2

function is_blackhole_request() {
    if (BLACKHOLE_COMMUNITY ~ bgp_community) then return true;
    return false;
}
{% endif %}""",
    },
]


async def install_default_templates(session: AsyncSession, ixp_id: uuid.UUID) -> None:
    """Install the default template set for a newly created IXP"""
    for tmpl in DEFAULT_TEMPLATES:
        session.add(
            RouteServerTemplate(
                ixp_id=ixp_id,
                filename=tmpl["filename"],
                content=tmpl["content"],
                description=tmpl["description"],
                is_protected=tmpl["is_protected"],
            )
        )
    await session.flush()
