"""Default BIRD templates installed for every new IXP.

Set euro-ix: tabla y pipe por peer, rs client, large communities de filtrado,
filtrado por ASN de origen y por prefijos, y RPKI opcional.

La logica de filtrado es contraintuitiva a proposito: el filtro de import NUNCA
rechaza, marca con una large community (routeserverasn, 1101, *) y acepta. Quien
descarta es el pipe hacia master, con f_export_to_master. Asi un looking glass
puede mostrar "esta ruta la recibi y la filtre por esta razon"; si se rechazara
en el import, la ruta no existiria y no habria nada que explicar.

La migracion a3b4c5d6e7f8 contiene un snapshot historico de los templates
anteriores. Esta es la fuente canonica para IXPs nuevos creados via setup
"""

import uuid

from sqlalchemy.ext.asyncio import AsyncSession

from ixforge.models.rs_template import RouteServerTemplate

DEFAULT_TEMPLATES: list[dict[str, object]] = [
    {
        "filename": "bird.conf.j2",
        "description": "Esqueleto BIRD 2.x: globals, funciones, RPKI y los peers de ambas familias",
        "is_protected": True,
        "content": r"""# BIRD 2.x configuration for {{ route_server.name }}
# Generated by IXForge Core at {{ generated_at }}
# Config hash: {{ config_hash }}
# DO NOT EDIT MANUALLY - this file is managed by IXForge

timeformat base     iso long;
timeformat log      iso long;
timeformat protocol iso long;
timeformat route    iso long;

log syslog all;
log stderr { error, fatal };

define routeserverasn = {{ route_server.asn }};
{% if route_server.ip_v4 %}
define routeserveraddress4 = {{ route_server.ip_v4 }};
{% endif %}
{% if route_server.ip_v6 %}
define routeserveraddress6 = {{ route_server.ip_v6 }};
{% endif %}

router id {{ route_server.router_id }};

# ignore interface up/down events
protocol device { }

{% include "functions/communities.j2" %}
{% include "filters/bogons.j2" %}
{% include "functions/common.j2" %}
{% include "functions/transit.j2" %}
{% include "functions/announce_control.j2" %}
{% include "filters/to_master.j2" %}
{% if route_server.rpki_enabled %}
{% include "protocols/rpki.j2" %}
{% endif %}
{% if route_server.ip_v4 %}
{% with af = 4 %}
{% include "protocols/rs_client.j2" %}
{% for peer in peers_v4 %}
{% include "protocols/bgp_peer.j2" %}
{% endfor %}
{% for peer in rs_peers_v4 %}
{% include "protocols/rs_peer.j2" %}
{% endfor %}
{% endwith %}
{% endif %}
{% if route_server.ip_v6 %}
{% with af = 6 %}
{% include "protocols/rs_client.j2" %}
{% for peer in peers_v6 %}
{% include "protocols/bgp_peer.j2" %}
{% endfor %}
{% for peer in rs_peers_v6 %}
{% include "protocols/rs_peer.j2" %}
{% endfor %}
{% endwith %}
{% endif %}
""",
    },
    {
        "filename": "functions/communities.j2",
        "description": "Defines de large communities del esquema euro-ix",
        "is_protected": False,
        "content": r"""# Communities del esquema euro-ix
# https://github.com/euro-ix/rs-workshop-july-2017/wiki/Route-Server-BGP-Community-usage

# Filtradas: el pipe hacia master descarta todo lo que lleve (routeserverasn, 1101, *)
define IXP_LC_FILTERED_PREFIX_LEN_TOO_LONG      = ( routeserverasn, 1101, 1  );
define IXP_LC_FILTERED_PREFIX_LEN_TOO_SHORT     = ( routeserverasn, 1101, 2  );
define IXP_LC_FILTERED_BOGON                    = ( routeserverasn, 1101, 3  );
define IXP_LC_FILTERED_BOGON_ASN                = ( routeserverasn, 1101, 4  );
define IXP_LC_FILTERED_AS_PATH_TOO_LONG         = ( routeserverasn, 1101, 5  );
define IXP_LC_FILTERED_AS_PATH_TOO_SHORT        = ( routeserverasn, 1101, 6  );
define IXP_LC_FILTERED_FIRST_AS_NOT_PEER_AS     = ( routeserverasn, 1101, 7  );
define IXP_LC_FILTERED_NEXT_HOP_NOT_PEER_IP     = ( routeserverasn, 1101, 8  );
define IXP_LC_FILTERED_IRRDB_PREFIX_FILTERED    = ( routeserverasn, 1101, 9  );
define IXP_LC_FILTERED_IRRDB_ORIGIN_AS_FILTERED = ( routeserverasn, 1101, 10 );
define IXP_LC_FILTERED_PREFIX_NOT_IN_ORIGIN_AS  = ( routeserverasn, 1101, 11 );
define IXP_LC_FILTERED_RPKI_UNKNOWN             = ( routeserverasn, 1101, 12 );
define IXP_LC_FILTERED_RPKI_INVALID             = ( routeserverasn, 1101, 13 );
define IXP_LC_FILTERED_TRANSIT_FREE_ASN         = ( routeserverasn, 1101, 14 );
define IXP_LC_FILTERED_TOO_MANY_COMMUNITIES     = ( routeserverasn, 1101, 15 );

# Informativas
define IXP_LC_INFO_RPKI_VALID       = ( routeserverasn, 1000, 1  );
define IXP_LC_INFO_RPKI_UNKNOWN     = ( routeserverasn, 1000, 2  );
define IXP_LC_INFO_RPKI_NOT_CHECKED = ( routeserverasn, 1000, 3  );
define IXP_LC_INFO_RPKI_INVALID     = ( routeserverasn, 1000, 4  );

define IXP_LC_INFO_IRRDB_VALID         = ( routeserverasn, 1001, 1  );
define IXP_LC_INFO_IRRDB_NOT_CHECKED   = ( routeserverasn, 1001, 2  );
define IXP_LC_INFO_IRRDB_MORE_SPECIFIC = ( routeserverasn, 1001, 3  );

define IXP_LC_INFO_IRRDB_FILTERED_LOOSE  = ( routeserverasn, 1001, 1000 );
define IXP_LC_INFO_IRRDB_FILTERED_STRICT = ( routeserverasn, 1001, 1001 );
define IXP_LC_INFO_IRRDB_PREFIX_EMPTY    = ( routeserverasn, 1001, 1002 );

define IXP_LC_INFO_SAME_AS_NEXT_HOP = ( routeserverasn, 1001, 1200 );

# forma large del tipo de miembro, para IXPs con ASN de 4 bytes que no entra
# en una community estandar
define IXP_LC_INFO_MEMBER_TYPE_BASE = ( routeserverasn, 1002, 0 );
""",
    },
    {
        "filename": "filters/bogons.j2",
        "description": "Sets de martians IPv4 e IPv6",
        "is_protected": False,
        "content": r"""# Martians, listas del patron euro-ix

define MARTIANS_V4 = [
    0.0.0.0/32-,            # rfc5735 Special Use IPv4 Addresses
    0.0.0.0/0{0,7},         # rfc1122 3.2.1.3
    10.0.0.0/8+,            # rfc1918
    100.64.0.0/10+,         # rfc6598 Shared Address Space
    127.0.0.0/8+,           # rfc1122 loopback
    169.254.0.0/16+,        # rfc3927 link-local
    172.16.0.0/12+,         # rfc1918
    192.0.0.0/24+,          # rfc6890
    192.0.2.0/24+,          # rfc5737 TEST-NET-1
    192.168.0.0/16+,        # rfc1918
    198.18.0.0/15+,         # rfc2544 benchmarking
    198.51.100.0/24+,       # rfc5737 TEST-NET-2
    203.0.113.0/24+,        # rfc5737 TEST-NET-3
    224.0.0.0/4+,           # rfc1112 multicast
    240.0.0.0/4+            # rfc6890 reservado
];

define MARTIANS_V6 = [
    ::/0,                   # default
    ::/96,                  # IPv4-compatible, deprecado por rfc4291
    ::/128,                 # unspecified
    ::1/128,                # loopback
    ::ffff:0.0.0.0/96+,     # IPv4-mapped
    ::224.0.0.0/100+,
    ::127.0.0.0/104+,
    ::0.0.0.0/104+,
    ::255.0.0.0/104+,
    0000::/8+,
    0200::/7+,              # OSI NSAP-mapped, deprecado por rfc4048
    3ffe::/16+,             # 6bone
    2001:db8::/32+,         # rfc3849 documentacion
    2002:e000::/20+,        # 6to4 invalido (multicast)
    2002:7f00::/24+,        # 6to4 invalido (loopback)
    2002:0000::/24+,        # 6to4 invalido (default)
    2002:ff00::/24+,
    2002:0a00::/24+,        # 6to4 invalido (10/8)
    2002:ac10::/28+,        # 6to4 invalido (172.16/12)
    2002:c0a8::/32+,        # 6to4 invalido (192.168/16)
    fc00::/7+,              # rfc4193 ULA
    fe80::/10+,             # link-local
    fec0::/10+,             # site-local, deprecado por rfc3879
    ff00::/8+               # multicast
];
""",
    },
    {
        "filename": "functions/common.j2",
        "description": "Funciones comunes: avoid_martians y honor_graceful_shutdown",
        "is_protected": False,
        "content": r"""# Funciones comunes

function avoid_martians4() {
    if net ~ MARTIANS_V4 then return false;
    return true;
}

function avoid_martians6() {
    if net ~ MARTIANS_V6 then return false;
    return true;
}

function honor_graceful_shutdown() {
    if (65535, 0) ~ bgp_community then {
        bgp_local_pref = 0;
    }
}
""",
    },
    {
        "filename": "functions/transit.j2",
        "description": "ASNs transit-free y el filtro que los detecta en el AS path",
        "is_protected": False,
        "content": r"""# ASNs transit-free, inspirado en http://bgpfilterguide.nlnog.net/guides/no_transit_leaks/
# Esta lista envejece: es editable a proposito para poder actualizarla sin un release

define TRANSIT_ASNS = [ 174, 701, 1299, 2914, 3257, 3320, 3356, 3491, 4134, 5511, 6453, 6461, 6762, 6830, 7018 ];

function filter_has_transit_path()
int set transit_asns;
{
    transit_asns = TRANSIT_ASNS;
    if (bgp_path ~ transit_asns) then {
        bgp_large_community.add( IXP_LC_FILTERED_TRANSIT_FREE_ASN );
        return true;
    }

    return false;
}
""",
    },
    {
        "filename": "functions/announce_control.j2",
        "description": "ixp_community_filter: control de anuncio selectivo por communities",
        "is_protected": False,
        "content": r"""# Control de anuncio selectivo por communities
# Se evalua en el pipe master -> tabla del peer, o sea decide a quien se le
# anuncia cada ruta segun lo que el miembro que la origino haya pedido

function ixp_community_filter(int peerasn)
{
    # las rutas que no vienen de BGP no se propagan
    if !(source = RTS_BGP) then
        return false;

    # 1. no anunciar a un peer especifico, maxima prioridad
    if (peerasn <= 65535) && (0, peerasn) ~ bgp_community then
        return false;
    if (routeserverasn, 0, peerasn) ~ bgp_large_community then
        return false;

    # 2. no anunciar a nadie, con excepciones
{% if route_server.asn <= 65535 %}
    bool deny_all_std = (0, routeserverasn) ~ bgp_community;
{% else %}
    # el ASN del IXP no entra en una community estandar: solo quedan las large
    bool deny_all_std = false;
{% endif %}
    bool deny_all_lrg = (routeserverasn, 0, 0) ~ bgp_large_community;

    if deny_all_std || deny_all_lrg then {
        # excepcion: anunciar a todos
{% if route_server.asn <= 65535 %}
        if (routeserverasn, routeserverasn) ~ bgp_community then
            return true;
{% endif %}
        if (routeserverasn, 1, 0) ~ bgp_large_community then
            return true;

        # excepcion: anunciar a este peer
{% if route_server.asn <= 65535 %}
        if (peerasn <= 65535) && (routeserverasn, peerasn) ~ bgp_community then
            return true;
{% endif %}
        if (routeserverasn, 1, peerasn) ~ bgp_large_community then
            return true;

        return false;
    }

    # 3. por defecto se anuncia
    return true;
}
""",
    },
    {
        "filename": "filters/to_master.j2",
        "description": "f_export_to_master: el unico lugar donde se descarta lo marcado",
        "is_protected": False,
        "content": r"""# El unico lugar donde se descarta: todo lo marcado como filtrado muere aca
filter f_export_to_master
{
    if bgp_large_community ~ [( routeserverasn, 1101, * )] then reject;
    accept;
}
""",
    },
    {
        "filename": "protocols/rpki.j2",
        "description": "Tablas ROA y protocolos RPKI contra los servidores RTR",
        "is_protected": False,
        "content": r"""# Validacion RPKI via RTR
roa4 table roa_v4;
roa6 table roa_v6;

{% for server in route_server.rpki_servers %}
protocol rpki rpki_{{ server.slug }} {
    roa4 { table roa_v4; };
    roa6 { table roa_v6; };
    remote "{{ server.host }}" port {{ server.port }};
{% if server.refresh_time %}
    refresh keep {{ server.refresh_time }};
{% endif %}
{% if server.retry_time %}
    retry keep {{ server.retry_time }};
{% endif %}
{% if server.expire_time %}
    expire keep {{ server.expire_time }};
{% endif %}
}

{% endfor %}
""",
    },
    {
        "filename": "protocols/rs_client.j2",
        "description": "Template BGP para clientes del route server: rs client, source address, passive",
        "is_protected": False,
        "content": r"""template bgp tb_rsclient_v{{ af }} {
    local as routeserverasn;
{% if af == 4 %}
    source address routeserveraddress4;
{% else %}
    source address routeserveraddress6;
{% endif %}
{% if route_server.passive_sessions %}
    passive yes;
{% endif %}

    # le da tiempo al RTR a poblarse antes de que levanten las sesiones
    connect delay time 30;

    # pass through de communities well-known de rfc1997
    interpret communities off;

{% if af == 4 %}
    ipv4 {
{% if route_server.rpki_enabled %}
        # sin import table, cuando cambian o expiran las ROAs BIRD no puede
        # reevaluar el filtro de import sobre las rutas ya recibidas sin pedirle
        # un route refresh al peer
        import table on;
{% endif %}
        export all;
    };
{% else %}
    ipv6 {
{% if route_server.rpki_enabled %}
        import table on;
{% endif %}
        export all;
    };
{% endif %}

    rs client;
}
""",
    },
    {
        "filename": "protocols/bgp_peer.j2",
        "description": "Bloque por peer miembro: tabla, filtro import, filtro export, protocolo y pipe",
        "is_protected": False,
        "content": r"""# {{ peer.member_name | bird_str }} (AS{{ peer.peer_asn }}) en {{ peer.peer_ip }}
{% if af == 4 %}
ipv4 table t_{{ peer.slug }};
{% else %}
ipv6 table t_{{ peer.slug }};
{% endif %}

filter f_import_{{ peer.slug }}
{% if peer.prefixes is not none %}
prefix set allnet;
{% endif %}
ip set allips;
int set allas;
{
{% if af == 4 %}
    if ( net ~ [ 0.0.0.0/0{25,32} ] ) then {
{% else %}
    if ( net ~ [ ::/0{49,128} ] ) then {
{% endif %}
        bgp_large_community.add( IXP_LC_FILTERED_PREFIX_LEN_TOO_LONG );
        accept;
    }

{% if af == 4 %}
    if !(avoid_martians4()) then {
{% else %}
    if !(avoid_martians6()) then {
{% endif %}
        bgp_large_community.add( IXP_LC_FILTERED_BOGON );
        accept;
    }

    if( bgp_path.len < 1 ) then {
        bgp_large_community.add( IXP_LC_FILTERED_AS_PATH_TOO_SHORT );
        accept;
    }

    if (bgp_path.first != {{ peer.peer_asn }} ) then {
        bgp_large_community.add( IXP_LC_FILTERED_FIRST_AS_NOT_PEER_AS );
        accept;
    }

    allips = [ {{ peer.all_peer_ips | join(', ') }} ];

    if !( from = bgp_next_hop ) then {
        if( bgp_next_hop ~ allips ) then {
            bgp_large_community.add( IXP_LC_INFO_SAME_AS_NEXT_HOP );
        } else {
            bgp_large_community.add( IXP_LC_FILTERED_NEXT_HOP_NOT_PEER_IP );
            accept;
        }
    }

    if filter_has_transit_path() then accept;

    if( bgp_path.len > 64 ) then {
        bgp_large_community.add( IXP_LC_FILTERED_AS_PATH_TOO_LONG );
        accept;
    }

    allas = [ {{ peer.origin_asns | join(', ') }} ];

    if !(bgp_path.last_nonaggregated ~ allas) then {
        bgp_large_community.add( IXP_LC_FILTERED_IRRDB_ORIGIN_AS_FILTERED );
        accept;
    }

{% if route_server.rpki_enabled %}
    if ( roa_check(roa_v{{ af }}, net, bgp_path.last) = ROA_VALID ) then {
        bgp_large_community.add( IXP_LC_INFO_RPKI_VALID );
    } else {
        if ( roa_check(roa_v{{ af }}, net, bgp_path.last) = ROA_INVALID ) then {
            bgp_large_community.add( IXP_LC_INFO_RPKI_INVALID );
{% if route_server.rpki_policy == 'reject_invalid' %}
            bgp_large_community.add( IXP_LC_FILTERED_RPKI_INVALID );
{% endif %}
        } else {
            bgp_large_community.add( IXP_LC_INFO_RPKI_UNKNOWN );
        }
    }
{% else %}
    bgp_large_community.add( IXP_LC_INFO_RPKI_NOT_CHECKED );
{% endif %}

{% if peer.prefixes is not none %}
    allnet = [ {{ peer.prefixes | join(', ') }} ];

    if ! (net ~ allnet) then {
        bgp_large_community.add( IXP_LC_FILTERED_IRRDB_PREFIX_FILTERED );
        bgp_large_community.add( IXP_LC_INFO_IRRDB_FILTERED_STRICT );
        accept;
    } else {
        bgp_large_community.add( IXP_LC_INFO_IRRDB_VALID );
    }
{% else %}
    bgp_large_community.add( IXP_LC_INFO_IRRDB_NOT_CHECKED );
{% endif %}

    honor_graceful_shutdown();

{% if peer.member_type_community %}
{% if route_server.asn <= 65535 %}
    bgp_community.add( (routeserverasn, {{ peer.member_type_community }}) );
{% else %}
    # el ASN del IXP no entra en una community estandar (16 bits), se usa la
    # forma large equivalente
    bgp_large_community.add( (routeserverasn, 1002, {{ peer.member_type_community }}) );
{% endif %}
{% endif %}

    accept;
}

# el export strippea nuestras propias communities de filtrado y looking glass.
# Las dos formas: dejar pasar las estandar (routeserverasn, *) filtra menos de
# lo que el operador cree, porque las de control de anuncio y las de marca de
# upstream llegarian al miembro
filter f_export_{{ peer.slug }}
{
    bgp_large_community.delete( [( routeserverasn, *, * )] );
{% if route_server.asn <= 65535 %}
    bgp_community.delete( [( routeserverasn, * )] );
{% endif %}
    accept;
}

protocol bgp pb_{{ peer.slug }} from tb_rsclient_v{{ af }} {
    description "{{ peer.member_name | bird_str }}";
    neighbor {{ peer.peer_ip }} as {{ peer.peer_asn }};

{% if af == 4 %}
    ipv4 {
{% else %}
    ipv6 {
{% endif %}
{% if peer.max_prefixes %}
        import limit {{ peer.max_prefixes }} action restart;
{% endif %}
        import filter f_import_{{ peer.slug }};
        table t_{{ peer.slug }};
        export filter f_export_{{ peer.slug }};
    };
}

protocol pipe pp_{{ peer.slug }} {
    description "Pipe for {{ peer.member_name | bird_str }}";
{% if af == 4 %}
    table master4;
{% else %}
    table master6;
{% endif %}
    peer table t_{{ peer.slug }};
    import filter f_export_to_master;
    export where ixp_community_filter({{ peer.peer_asn }});
}
""",
    },
    {
        "filename": "protocols/rs_peer.j2",
        "description": "Bloque por peer que no es miembro: upstream, colector o especial",
        "is_protected": False,
        "content": r"""# {{ peer.name | bird_str }} (AS{{ peer.peer_asn }}, {{ peer.peer_type }})
{% if af == 4 %}
ipv4 table t_{{ peer.slug }};
{% else %}
ipv6 table t_{{ peer.slug }};
{% endif %}

protocol bgp pb_{{ peer.slug }} {
    description "{{ peer.name | bird_str }}";
    local as {{ peer.local_asn }};
    neighbor {{ peer.peer_ip }} as {{ peer.peer_asn }};
{% if peer.passive %}
    passive yes;
{% endif %}

{% if af == 4 %}
    ipv4 {
{% else %}
    ipv6 {
{% endif %}
{% if peer.max_prefixes %}
        import limit {{ peer.max_prefixes }} action restart;
{% endif %}
        import filter {
{% if peer.mark_community %}
            bgp_community.add( ({{ peer.mark_community | bird_community }}) );
{% endif %}
            accept;
        };
        export all;
        table t_{{ peer.slug }};
    };
}

protocol pipe pp_{{ peer.slug }} {
    description "Pipe for {{ peer.name | bird_str }}";
{% if af == 4 %}
    table master4;
{% else %}
    table master6;
{% endif %}
    peer table t_{{ peer.slug }};
    import all;
{% if peer.mark_community %}
    export where !(bgp_community ~ [({{ peer.mark_community | bird_community }})]);
{% else %}
    export all;
{% endif %}
}
""",
    },
]


async def install_default_templates(session: AsyncSession, ixp_id: uuid.UUID) -> None:
    """Install the default template set for a newly created IXP"""
    for tmpl in DEFAULT_TEMPLATES:
        session.add(
            RouteServerTemplate(
                ixp_id=ixp_id,
                filename=tmpl["filename"],
                content=tmpl["content"],
                description=tmpl["description"],
                is_protected=tmpl["is_protected"],
            )
        )
    await session.flush()
